### ISSUE TITLE
New project gulp error

### ISSUE THREAD

**Issue by daveaccent** [AccentDesign/karma-css#17]
Strange one, gulp tasks will fail on new installs unless you define a primary and secondary colour in a new _variables.scss file. Not sure why this isn't working.

**Comment by stuartaccent** [comment]
it sounds like you are defining a new colours variable without these two colours.

ie in https://github.com/AccentDesign/karma-css/blob/master/scss/_variables.scss#L73
this has a `!default` which means only declare if this variable does not exist. 
The core is expecting these to be there in buttons and such https://github.com/AccentDesign/karma-css/blob/master/scss/_variables.scss#L95

So if you have declared it without these colours then it will fail.

**Comment by stuartaccent** [comment]
Does that help @daveaccent :)

**Comment by daveaccent** [comment]
Aha, perfect and it makes sense, thank you.
