### ISSUE TITLE
Addition of Colors New Default colour palette as variables

### ISSUE THREAD

**Issue by ghost** [AccentDesign/karma-css#31]
/*  A nicer colour palette for the web via http://clrs.cc/  */
/* Cool */
$aqua: #7FDBFF;
$blue: #0074D9;
$navy: #001F3F;
$teal: #39CCCC;
$green: #2ECC40;
$olive: #3D9970;
$lime: #01FF70;

/* Warm */
$yellow: #FFDC00;
$orange: #FF851B;
$red: #FF4136;
$fuchsia: #F012BE;
$purple: #B10DC9;
$maroon: #85144B;

/* Grayscale */
$white: #fff;
$silver: #ddd;
$gray: #aaa;
$black: #111;

**Comment by stuartaccent** [comment]
https://github.com/AccentDesign/karma-css/pull/34
