### ISSUE TITLE
Addition of touch device-friendly hover & transition mixins

### ISSUE THREAD

**Issue by ghost** [AccentDesign/karma-css#33]
/*
 * Provide a hover effect for non-touch devices, turn it into an Active state for mobile, and maintain a fallback. 
 * @requires Modernizr or another JS to add the appropriate .no-touch/.touch classes to the <body> element
 * Adds styles via @content
 */
@mixin touch-hover() {
    .no-js &:hover, // the fallback
    .no-js &:focus,
    .js.no-touch &:hover, // enhanced for no-touch
    .js.no-touch &:focus,
    .js.touch &:active { // relay same styles to active & focus for touch devices
        @content;
    }
}

/*
 * Applies transition to element but removes it from the same element on touch devices.
 * Useful for making all pseudo hover effects on mobile instant on click.
 */
@mixin transition-no-touch($properties) {
    transition: $properties;
    .js.touch & { transition: none; }
}

**Comment by stuartaccent** [comment]
https://github.com/AccentDesign/karma-css/pull/34
