### ISSUE TITLE
Addition of heading classes

### ISSUE THREAD

**Issue by ghost** [AccentDesign/karma-css#35]
h1, .h1 { }
h2, .h2 { }
h3, .h3 { }
h4, .h4 { }
h5, .h5 { }
h6, .h6 { }

These are extremely useful to keep markup semantic but adjust the appearance of a heading by "disguising" it

**Comment by stuartaccent** [comment]
Cool. Will do

**Comment by stuartaccent** [comment]
e18c2ab1b99a04b7541a11825cc720fa673d9292
