### ISSUE TITLE
Addition of a .list-inline class to <ul> & <ol>

### ISSUE THREAD

**Issue by ghost** [AccentDesign/karma-css#37]
<ul class="list-inline">
  <li>Lorem ipsum</li>
  <li>Phasellus iaculis</li>
  <li>Nulla volutpat</li>
</ul>

Removes any list style, padding and displays items inline. Useful for lists that aren;t really listed like navigation or groups of social links

**Comment by daveaccent** [comment]
You can include your own style to your project or KarmaCSS can help with the following example:

```
<ul class="list-style-none">
  <li class="d-inline"></li> <!-- display inline -->
</ul>
```
