### ISSUE TITLE
Fix gird columns

### ISSUE THREAD

**Issue by ghost** [AccentDesign/karma-css#38]
Encountered an issue where i tried to simply use .col or .col-12 so that an element spanned all columns on all screen sizes but it didn't work.

I had to enter a larger breakpoint column class as well for it to work ie. col-12 col-lg-12

**Comment by daveaccent** [comment]
Example please as this seems to work okay for haas.co.uk

**Comment by ghost** [comment]
![screen shot 2017-10-02 at 3 52 29 pm 2](https://user-images.githubusercontent.com/20127293/31083517-cd67d242-a789-11e7-84ec-e8d00e89e69e.png)

**Comment by stuartaccent** [comment]
Hi, 

What is included in your variables file as there is no `col-*` css applied of any kind and in the latest css includes the following `col` & `.col-12`:

https://github.com/AccentDesign/karma-css/blob/master/dist/karma.css#L199
https://github.com/AccentDesign/karma-css/blob/master/dist/karma.css#L211
https://github.com/AccentDesign/karma-css/blob/master/dist/karma.css#L306

Also is it in your un-minified css and not your minified? as we were all using gulp-csso to minify and recently discovered a lot of issues with it so moved to gulp-cssmin.

Ty

**Comment by stuartaccent** [comment]
Also make sure you have usable breakpoints set up as the grid is built using media queries in particular the zero based starting point:

https://github.com/AccentDesign/karma-css/blob/master/scss/_variables.scss#L37

**Comment by ghost** [comment]
Interpreted the documentation at http://karmacss.com/documentation/grid/ to mean i could use a col-12 class in isolation.

Also the grid has no facility to push & pull columns to reorder them. This is something a find extremely useful and use more than the offset functions.

I pulled down my copy of Karma CSS from the starter project an it's package.json still prescribes gulp-csso as a dependency instead of cssmin.

**Comment by stuartaccent** [comment]
Will make the docs a bit clearer when i get a chance.

Push and pull has been implemented already by the means of `order-*` see http://karmacss.com/documentation/grid/#47

The starter project needs updating i guess, this issue only raised itself last week and not had a chance to sort it yet

Ty

**Comment by stuartaccent** [comment]
Tweaked the starter project at https://github.com/AccentDesign/karma-css-starter/commit/a1cf47b69e3bd3651877ce0dd3bbd8be46e3e83f
