### ISSUE TITLE
Consider replacing input[type=...] classes with single .form-control

### ISSUE THREAD

**Issue by stuartaccent** [AccentDesign/karma-css#39]
obviously this will have a big impact

**Comment by daveaccent** [comment]
I think it needs to be done as it imposes less on the default display of the template.

**Comment by stuartaccent** [comment]
@daveaccent, yeh i agree just wanted a second opinion, i will start a vers 2 branch as it seems small but is quite a hefty breaking change, it will make it simpler to override too as input[type] is higher than a class

![screen shot 2017-10-27 at 20 17 23](https://user-images.githubusercontent.com/20105514/32121282-ee9db67e-bb53-11e7-80b1-9c2063d940c8.png)

**Comment by daveaccent** [comment]
@stuartaccent Yeah good point and keep up the awesome work.

**Comment by stuartaccent** [comment]
#74 fixes one half of this, now we are only styling the `type` selector ie `[type="text"]` so now a single class will override the styles of the input

**Comment by stuartaccent** [comment]
closing for now
