### ISSUE TITLE
Spacing sizes

### ISSUE THREAD

**Issue by nickaccent** [AccentDesign/karma-css#41]
Consider adding sizing to spacers, i.e.

mt-2h would become mt-xs-2h, mt-sm-2h,  mt-md-2h, mt-lg-2h or mt-xl-2h.

This would make them much more usable and breakpoint responsive.

**Comment by stuartaccent** [comment]
Hi nick, 

Those classes are defined in the project you are working on and are not part of karma-css. we did toy with the idea of adding them a while ago but felt the volume of classes they produce was enormous compared to the base karma, ie

m-* mt-* mr-* mb-* ml-* mx-* my-* = 7
times that by 5 breakpoints = 35
say you define 10 sizes ends up with 350 classes in the css just for margin, then there is padding too. 

This is why we just put in the docs you could do it and provided mixins to assist http://karmacss.com/documentation/mixins/#13

Stu
