### ISSUE TITLE
Addition of a breakpoint mixin function

### ISSUE THREAD

**Issue by ghost** [AccentDesign/karma-css#78]
A super useful addition for me would be the addition of a breakpoint mixin function that can access a value within the $grid-breakpoints array by it's name key, like color("white").

For example, 

breakpoint("xl")

This way i can use the same breakpoint values in my media queries that are used for the grid without rewriting them 😊

**Comment by daveaccent** [comment]
Good request but we already use the Sass mixins:

```
@include media-breakpoint-up(xs) { ... }
@include media-breakpoint-up(sm) { ... }
@include media-breakpoint-up(md) { ... }
@include media-breakpoint-up(lg) { ... }
@include media-breakpoint-up(xl) { ... }

// Example usage:
@include media-breakpoint-up(sm) {
    .some-class {
        display: block;
    }
}
```
Let us know if you need more.
