### ISSUE TITLE
Review button class

### ISSUE THREAD

**Issue by stuartaccent** [AccentDesign/karma-css#9]
Should we continue to target all the buttons like:
```scss
.button,
button,
input[type="submit"],
input[type="reset"],
input[type="button"] {
    ...
}
```
as there are hovers and additional colours just to save people adding `.button` or should we just use `.button` and strip out the bloat.

**Comment by stuartaccent** [comment]
what do you think @daveaccent ?

**Comment by stuartaccent** [comment]
i've already changed the docs @daveaccent so its not advertised that they all are like this

**Comment by daveaccent** [comment]
Strip out the bloat, the skeleton framework is already verbose

**Comment by bigmassa** [comment]
Cool

**Comment by bigmassa** [comment]
That's a breaking change so is in 1.1

**Comment by stuartaccent** [comment]
https://github.com/AccentDesign/karma-css/commit/a08a7389aa429b028b8ba4d0cc48582a9821e535
